version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GGCEmergencyFunction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-34z73s6fnbsl"
s3_prefix = "GGCEmergencyFunction"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
