AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Greengrass Core Emergency function

Metadata:
  AWS::ServerlessRepo::Application:
    Name: GGCEmergencyFunction
    Description: Greengrass Core Emergency function
    Author: lkirner
    SemanticVersion: 0.0.1

Resources:
  GGCEmergencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  GGCEmergencyFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GGCEmergencyFunction.Arn
  GGCEmergencyFunctionIamRole:
    Description: "Implicit IAM Role created for emergency function"
    Value: !GetAtt GGCEmergencyFunctionRole.Arn
