---
- name: Update apt repository
  apt:
    update_cache: yes

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Install openjdk-8-jdk
  apt:
    name: openjdk-8-jdk
    state: present

- name: Install docker
  apt:
    name: docker.io
    state: present

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Install python3
  apt:
    name: python3
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Add user to docker group # (optional - dev)
  shell: usermod -aG docker {{ ansible_user }}

- name: Add user to plugdev group
  shell: usermod -aG plugdev {{ ansible_user }}

- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: reboot
