apiVersion: v1
kind: Pod
metadata:
  name: detector
  namespace: default
  labels:
    app: detector
spec:
  containers:
    - name: detector
      image: registry.inovex.de:4567/lkirner/edge-platforms-evaluation/detector:latest
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
      securityContext:
        privileged: true # <-- pod requires access to USB ports
      volumeMounts:
        - mountPath: /dev/bus/usb
          name: usb
  nodeSelector:
    type: tpu # <-- pod requires TPU attached via USB port
  volumes:
    - name: usb
      hostPath:
        path: /dev/bus/usb
  imagePullSecrets:
    - name: gitlab-pull-secrets
