---
apiVersion: iofog.org/v2
kind: Application
metadata:
  name: detector
spec:
  microservices:
    - name: detector
      agent:
        name: agent-1
      config: {}
      images:
        arm: registry.inovex.de:4567/lkirner/edge-platforms-evaluation/detector:latest
        registry: local # <-- ioFog no able to pull from private registry with different port
      container:
        rootHostAccess: true # <-- like privileged (network is also host network now)
        volumes:
          - hostDestination: /dev/bus/usb
            containerDestination: /dev/bus/usb
            accessMode: 'rw'
        ports: []
        env:
          - key: MQTT_HOST
            value: 192.168.178.151
          - key: PYTHONUNBUFFERED
            value: "1"
