---
k3s_version: v1.21.1+k3s1

ansible_connection: ssh
ansible_user: ubuntu
ansible_port: 22 
ansible_become_pass: "{{ lookup('env', 'SUDO_PASSWORD') }}"
ansible_ssh_private_key_file: ./keys/id_rsa

systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
